### ISSUE TITLE
Epic 0 Требования

### ISSUE THREAD

**Issue by FantasmasDev** [FantasmasDev/sugar-hunter#10]
- [x] Проект компилируется и запускается без сбоев и ошибок.

- [x] Нижняя панель навигации видна при запуске приложения. 

- [x] Внешний вид панели навигации соответствует дизайну как в светлой, так и в тёмной теме.

- [x]  Нажатие на табы панели переключает экраны («заглушки») в контейнере.

- [x] Переход на экран «Команда» осуществляется нажатием на соответствующую вкладку нижней панели навигации.
